export const historiaData = {
  title: 'A História',
  paragraphs: [
    `A formação da Liga Municipal de Futebol de Taubaté (L. M. F. T.) ocorreu através de duas ligas que já existiam na cidade. A Liga de Futebol Norte de São Paulo (L. F. N. S. P.) que congregava as cidades da região do Vale do Paraíba e a Liga Suburbana de Futebol. A fundação da Liga Municipal de Futebol de Taubaté ocorreu em 1942, mas ela se efetivou em 1943. Durante dois anos não foi realizado nenhum campeonato devido à construção do estádio Félix Guisard, atualmente campo da CTI e os Jogos Abertos do Interior, que na ocasião era algo inédito.`,
    `Segundo Paulo Campos de Azevedo, no livro “Taubaté e o Futebol História”, A Liga Municipal de Futebol de Taubaté teve como antecedentes a Liga de Futebol Norte de São Paulo (1938) e a Liga Suburbana de Futebol (1941). A Liga Municipal de Futebol, iniciativa particular, foi fundada em 1938, com o nome originário de Liga de Futebol Norte de São Paulo (LFNSP) e congregava as principais cidades do Vale do Paraíba para a disputa de jogos amadores de futebol entre elas. Nesse mesmo ano, o Esporte Clube Taubaté organizou e fez disputar um campeonato municipal, sendo os integrantes União Juta Fabril, São João Futebol Clube, Esporte Clube Jacques Félix, União Operária Futebol Clube e outros. Era o primeiro fruto da Liga de Futebol Norte de São Paulo. No dia 16 de dezembro de 1941, surgia o futebolista Galdino Marcondes de Rezende, da fazenda Barreiro, trazendo uma ideia nova, a fundação da Liga Suburbana de Futebol.`,
    `Em 1945, o primeiro ano de disputa do campeonato, duas equipes foram campeãs, o Clube Atlético Ceteiense e o E. C. Taubaté que foi o campeão da região sendo o representando do Estado. Mas esse título foi válido apenas pela L. F. N. S. P. O Clube Atlético Ceteiense foi o primeiro campeão da Liga Municipal de Futebol de Taubaté.`,
    `O vereador Moacir de Alvarenga Peixoto apresentou na Câmara Municipal o projeto de utilidade pública para a fundação de uma entidade de futebol. E o primeiro presidente foi José Luiz de Almeida Soares, que na época era prefeito de Taubaté. Benedito Marcondes Ferreira, presidente que ficou por mais tempo na Liga, mudou a forma como era analisado o futebol amador, tanto que no seu período surgiram várias equipes e o campeonato chegou a contar com três divisões. “Um lutador emérito, batalhador, o homem que carregava sozinho nas costas a Liga de Taubaté”, ressaltou Horton Sidnei Cunha sobre o comportamento de Benedito Marcondes Ferreira. O futebol amador tinha uma ajuda do município, porém a Liga não tinha uma sede própria. A sede da Liga passou por vários locais desde a residência de Benedito Marcondes, a praça D. Epaminondas, R. Pedro Costa, R. Emílio Winther e após várias mudanças, ela se efetivou na Rodoviária Velha de Taubaté.`,
    `Após o mandato de Benedito Ferreira, Moacir Peixoto comandou a entidade por quatro anos, de 1969 a 1973. Durante seu mandato houve uma modernização na condução dos campeonatos da Liga. Geraldo Vicente de Melo, presidente entre 1993 e 1994 e diretor técnico entre 1994 e 2001, reformulou a estrutura do futebol amador da cidade tornando um dos mais competitivos da região. Devido às mudanças realizadas a Liga Municipal além de patrocinar o campeonato amador da cidade também teve condições de organizar uma competição regional, no fim da década de 90, chamada Copa Vale. Essa competição era realizada na década de 40 com a participação de equipes do Vale do Paraíba e era organizada pela Liga de Futebol Norte de São Paulo.`
  ],
  fonte:
    'Fonte: 60 anos de Futebol Amador em Taubaté - VIRGÍLIO RIBEIRO GERALDO'
}
